### PR TITLE
Configuration/Settings Method Implemented

### PR DESCRIPTION
**Pull request by StudioLE**
Complete at last! 👌

It's only taken me a month to find the time to do it...

`settings.json` is now the go to place to configure everything

- Here's a quick breakdown of the options:
- `consent: requested` determines whether or not to show the consent splash screen
- `consent: given` determines whether or not consent has been given so we can collect all their data
- `collect` enables you to individually configure which data items are/aren't collected. This will be super useful for GDPR compliance etc
- `dashboard: id` controls the link in the menu bar
- `export: method` determines which export method to use. Currently only googleSheets...
- `export: googleSheets` is for the Sheet id and tab
- `export: googleSheetsServiceAccount` is for all the ServiceAccount credentials

Issues #12 and #20 are therefore now fixed.

I have however hit a snag with #11.

On my local machine everything works perfectly in DynamoSandbox `2.0` and `2.1`. It works in Revit too (although Player is currently untested).

When I copy the `Binoculars` package to a different machine it runs with all the settings loading, MessageBoxes appearing, and menu bar working but when I hit run on a graph it just crashes...? Further investigation required... Perhaps someone else can advise?

### CODE REVIEW

**Comment by StudioLE** [comment]
I'm anticipating quite a few merge conflicts when we resolve the issues delaying PR #28 - but it should be manageable to weave them together.

**Comment by StudioLE** [comment]
The latest commit (16f09f2) is a fix for issue #23.

We now have methods to handle common exceptions, such as when `settings.json` can't be read, is misconfigured, or we can't connect to the ipinfo.io or Google APIs.

For all common exceptions messages and possible solutions are written to the `debug` output in Visual Studio which should help diagnose issues.

Debug Output

Where it's possible to recover from an exception the application will continue. For example when an API calls fail.

If an exception can't be handled then the extension will cease loading but Dynamo should continue to work without issue. For example when loading settings.json fails.

We could in theory open an alert or dialog box within the UI or implement a logging framework such as [log4net](https://logging.apache.org/log4net/) but for the moment simply logging to debug within Visual Studio felt like the best approach.

**Comment by StudioLE** [comment]
Complete (for the second time..) 👌

Binoculars can now be downloaded, installed and configured without ever touching Visual Studio.

Just download the package from [/releases](https://github.com/teamtreedyn/Binoculars/releases) and follow the [Getting Started Guide](https://github.com/teamtreedyn/Binoculars/blob/master/GETTING-STARTED.md)

Everything is configured via `settings.json` so it's super simple and portable.

Let me know if anyone has any issues. Feedback greatly appreciated.

@2adicted @WaynePatrickDalton @CaoimheLoftus

**Comment by Deep18795** [comment]
hi can you please help me how to put private key in this coding?
Capture

**Pull request merged**
